### ISSUE TITLE
Problem with static server

### ISSUE THREAD

**Issue by jifeon** [apsavin/bnsf#19]
1. run gulp
2. include some styl file into the build process
3. create a mistake in the file
4. try to continue the work :)

Current result: static server falls down and stops watching the files, if you break gulp work and run it again it won't help you, because static server process is detached. You need to stop the node process manually

Expected: 
1. static server continues working if an error happens. 
2. static server stops at the same time the gulp does.

**Comment by apsavin** [comment]
It's a problem with your gulpfile. See solution [here](https://github.com/apsavin/generator-bnsf/blob/master/app/templates/gulpfile.js).
